# The Default Profile
[profile.default]
solc_version = "0.8.17"
auto_detect_solc = false
optimizer_runs = 9999999
via_ir = true

# Configure remappings
remappings = [
  "@std=lib/forge-std/src/",
  "@solbase=lib/solbase/",
  "@keep=lib/keep/src/",
  "@kali=lib/rage-router/src"
]

[fuzz]
runs = 1_000

[profile.fuzz.ci]
runs = 100_000